import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test, type Page } from '@playwright/test';

/**
 * The Bluebook spectrum rail — geometry always, pixels against the reference.
 *
 * Two halves, deliberately separated:
 *
 * 1. GEOMETRY (always runs, needs no baseline). The rail replaced a flat divider
 *    under the top bar and under the question header, so regression looks like a
 *    rail that stopped spanning its host, one that floated above the host's edge,
 *    one whose fixed-pixel barcode started stretching with the container width,
 *    a divider colour creeping back underneath it, or a host whose surface drifted
 *    (the main header is paper white; the question strip is the reference gray).
 *
 * 2. PIXELS (the acceptance gate). The comparison is against the SUPPLIED
 *    REFERENCE CROPS in `e2e/fixtures/sat-rail-reference/`, never against our own
 *    output: a snapshot generated by the implementation can only ever prove the
 *    implementation agrees with itself. Until a crop is supplied it is skipped,
 *    with the exact file name it wants, so nothing silently locks an
 *    approximation — drop the crop in and the comparison starts enforcing it.
 *
 * Everything is measured at examZoom=1 / DPR=1 (asserted below), because screen
 * zoom scales the plane the rail is painted inside and would distort every
 * measurement, and because the crops are cut at that scale.
 */

const VIEWPORT = { width: 1440, height: 900 };
// This package is `type: module`, so specs load as ESM: no `__dirname`.
const REFERENCE_DIR = fileURLToPath(new URL('fixtures/sat-rail-reference', import.meta.url));
const RAIL = '[data-sat-color-rail="true"]';

/**
 * The four crops the reference supplies, anchored to each host's BOTTOM edge —
 * which is where the rail lives, so a crop may be the 3px rail alone or the whole
 * strip and still align. `states` is applied before the capture, in order.
 */
const REFERENCE_REGIONS = [
  {
    file: 'top-rail.png',
    anchor: 'header[role="banner"]',
    states: [] as string[],
  },
  {
    file: 'question-header-unmarked.png',
    anchor: 'question-header',
    states: ['unmarked'],
  },
  {
    file: 'question-header-marked.png',
    anchor: 'question-header',
    states: ['unmarked', 'marked'],
  },
  {
    file: 'question-header-eliminator-on.png',
    anchor: 'question-header',
    states: ['unmarked', 'marked', 'eliminator'],
  },
];

/** Width and height straight out of a PNG's IHDR — no decoder needed to guard size. */
function readPngSize(path: string): { width: number; height: number } {
  const header = readFileSync(path).subarray(16, 24);
  return { width: header.readUInt32BE(0), height: header.readUInt32BE(4) };
}

interface RailReading {
  hostBackground: string;
  hostBorderBottomColor: string;
  hostBox: { left: number; top: number; right: number; bottom: number; width: number; height: number };
  railBox: { left: number; top: number; right: number; bottom: number; height: number };
  railCount: number;
  railAriaHidden: string | null;
  railHasTabIndex: boolean;
  railPosition: string;
  railPointerEvents: string;
  railRadius: string;
  railIsLastChild: boolean;
  railBackgroundImage: string;
  railBackgroundColor: string;
  railBackgroundSize: string;
  railBackgroundRepeat: string;
  railUnobstructedByControls: boolean;
  light: string;
  blue: string;
  yellow: string;
}

async function readRails(page: Page) {
  return page.evaluate(() => {
    const rails = Array.from(document.querySelectorAll<HTMLElement>('[data-sat-color-rail="true"]'));
    const topbarHost = document.querySelector<HTMLElement>('header[role="banner"]');
    const questionHeaderHost =
      rails
        .map((rail) => rail.parentElement)
        .find((host) => host !== null && host !== topbarHost) ?? null;

    const read = (host: HTMLElement, readsTokensFrom: HTMLElement) => {
      const rail = host.querySelector<HTMLElement>('[data-sat-color-rail="true"]');
      if (!rail) throw new Error('A rail host rendered without its rail.');
      const hostBox = host.getBoundingClientRect();
      const railBox = rail.getBoundingClientRect();
      const railStyle = getComputedStyle(rail);
      // Custom properties only resolve inside the .sat-ui scope they are
      // declared in, so the probe that turns a token into rgb() has to live in
      // the host rather than in the document.
      const tokenToRgb = (token: string) => {
        const probe = document.createElement('span');
        probe.style.backgroundColor = `var(${token})`;
        // The probe reads the token itself, never the forced-colors repaint that
        // an ordinary element would get — the rail opts out of that repaint too.
        probe.style.setProperty('forced-color-adjust', 'none');
        readsTokensFrom.appendChild(probe);
        const value = getComputedStyle(probe).backgroundColor;
        probe.remove();
        return value;
      };
      return {
        hostBackground: getComputedStyle(host).backgroundColor,
        hostBorderBottomColor: getComputedStyle(host).borderBottomColor,
        hostBox: {
          left: hostBox.left,
          top: hostBox.top,
          right: hostBox.right,
          bottom: hostBox.bottom,
          width: hostBox.width,
          height: hostBox.height,
        },
        railBox: {
          left: railBox.left,
          top: railBox.top,
          right: railBox.right,
          bottom: railBox.bottom,
          height: railBox.height,
        },
        railCount: host.querySelectorAll('[data-sat-color-rail="true"]').length,
        railAriaHidden: rail.getAttribute('aria-hidden'),
        railHasTabIndex: rail.hasAttribute('tabindex'),
        railPosition: railStyle.position,
        railPointerEvents: railStyle.pointerEvents,
        railRadius: railStyle.borderTopLeftRadius,
        railIsLastChild: host.lastElementChild === rail,
        railBackgroundImage: railStyle.backgroundImage,
        railBackgroundColor: railStyle.backgroundColor,
        railBackgroundSize: railStyle.backgroundSize,
        railBackgroundRepeat: railStyle.backgroundRepeat,
        // The rail crosses the review control and the ABC eliminator, so no
        // control in its band may paint over it. A control above the band is
        // free; one that reaches into it must paint first — which is true for
        // an unpositioned control, and for a positioned one with z-index auto/0
        // that precedes the rail in the DOM (the rail is the host's last child).
        railUnobstructedByControls: Array.from(host.querySelectorAll<HTMLElement>('button')).every(
          (control) => {
            const box = control.getBoundingClientRect();
            if (box.height === 0 || box.bottom <= railBox.top) return true;
            const zIndex = getComputedStyle(control).zIndex;
            const stackingLevel = zIndex === 'auto' ? 0 : Number(zIndex);
            if (stackingLevel > 0) return false;
            return (
              rail.compareDocumentPosition(control) !== 0 &&
              (rail.compareDocumentPosition(control) & Node.DOCUMENT_POSITION_PRECEDING) !== 0
            );
          },
        ),
        light: tokenToRgb('--sat-rail-light'),
        blue: tokenToRgb('--sat-rail-blue'),
        yellow: tokenToRgb('--sat-rail-yellow'),
      };
    };

    if (!topbarHost || !questionHeaderHost) {
      throw new Error('The harness did not render both spectrum-rail hosts.');
    }
    return {
      topbar: read(topbarHost, topbarHost),
      questionHeader: read(questionHeaderHost, questionHeaderHost),
    };
  });
}

function expectFlushRail(name: string, rail: RailReading, expectedSurface: string) {
  // The main header is paper; the question strip is the reference's light gray.
  expect(rail.hostBackground, `${name} surface`).toBe(expectedSurface);
  // Exactly one rail, and it is decoration: no accessibility tree entry, no
  // tab stop, no pointer target.
  expect(rail.railCount, `${name} draws exactly one rail`).toBe(1);
  expect(rail.railAriaHidden, `${name} rail is decoration`).toBe('true');
  expect(rail.railHasTabIndex, `${name} rail is never focusable`).toBe(false);
  expect(rail.railPointerEvents, `${name} rail never takes a pointer`).toBe('none');
  expect(rail.railRadius, `${name} rail has square ends`).toBe('0px');
  // An overlay, painted last: it cannot reflow the header it closes, and the
  // controls it passes under cannot interrupt it.
  expect(rail.railPosition, `${name} rail is an overlay`).toBe('absolute');
  expect(rail.railIsLastChild, `${name} rail is painted over the row`).toBe(true);
  expect(rail.railUnobstructedByControls, `${name} rail is never cut by a control`).toBe(true);
  // Flush: the rail's bottom edge IS the host's bottom edge, with no gap.
  expect(Math.abs(rail.railBox.bottom - rail.hostBox.bottom), `${name} rail closes the host`).toBeLessThanOrEqual(0.5);
  expect(rail.railBox.top, `${name} rail sits inside the host`).toBeLessThan(rail.hostBox.bottom);
  // Full width: one continuous line, edge to edge, under the review control and
  // across to the ABC eliminator.
  expect(Math.abs(rail.railBox.left - rail.hostBox.left), `${name} rail starts at the host edge`).toBeLessThanOrEqual(0.5);
  expect(Math.abs(rail.railBox.right - rail.hostBox.right), `${name} rail ends at the host edge`).toBeLessThanOrEqual(0.5);
  // The reference band: a rule, never a hairline and never a band.
  expect(rail.railBox.height).toBeGreaterThanOrEqual(2);
  expect(rail.railBox.height).toBeLessThanOrEqual(4);
  // The reserved border is transparent: the bottom edge a student sees is the
  // rail alone, with no divider colour contributing pixels to it.
  expect(rail.hostBorderBottomColor, `${name} reserves its border transparently`).toBe('rgba(0, 0, 0, 0)');
  // The accents are really painted, from the shared tokens: a fallback fill or
  // a one-colour rule fails here.
  expect(rail.railBackgroundImage, `${name} rail paints the shared blue accent`).toContain(rail.blue);
  expect(rail.railBackgroundImage, `${name} rail paints the shared yellow accent`).toContain(rail.yellow);
  expect(rail.railBackgroundImage, `${name} rail paints the shared light gray`).toContain(rail.light);
  // Real light breaks: the host's own surface shows through the gaps, so the
  // rail itself paints no base colour behind them.
  expect(rail.railBackgroundImage, `${name} rail keeps its light breaks`).toContain('rgba(0, 0, 0, 0)');
  expect(rail.railBackgroundColor, `${name} rail has no solid base behind its breaks`).toBe('rgba(0, 0, 0, 0)');
}

/** Parses the `scale` component out of a computed transform. */
function transformScale(transform: string): number {
  if (transform === 'none') return 1;
  const match = /matrix\(([^)]+)\)/.exec(transform);
  if (!match) throw new Error(`Unsupported transform: ${transform}`);
  return Number(match[1]!.split(',')[0]!.trim());
}

test.use({ viewport: VIEWPORT });

test.beforeEach(async ({ page }) => {
  await page.goto('/__dev/sat-accessibility');
  await expect(page.getByTestId('sat-exam-shell')).toBeVisible({ timeout: 30_000 });
  // Screenshots compare glyph antialiasing too, so the web fonts must have
  // settled before the first capture.
  await page.waitForFunction(() => document.fonts.status === 'loaded');
});

test('measures at examZoom=1 and DPR=1, so the fixed pixel rail is undistorted', async ({ page }) => {
  const zoom = await page.evaluate(() => {
    const plane = document.querySelector<HTMLElement>('[data-sat-zoom-plane="true"]');
    return {
      attribute: plane?.getAttribute('data-sat-screen-zoom') ?? null,
      transform: plane ? getComputedStyle(plane).transform : null,
      dpr: window.devicePixelRatio,
    };
  });
  expect(zoom.attribute, 'the harness must not auto-fit for this suite').toBe('1');
  expect(transformScale(zoom.transform ?? 'none'), 'the exam plane must not be scaled').toBe(1);
  expect(zoom.dpr, 'reference crops are cut at DPR 1').toBe(1);
});

test('closes the top bar and the question header as one flush rule', async ({ page }) => {
  const readings = await readRails(page);
  expectFlushRail('top bar', readings.topbar, 'rgb(255, 255, 255)');
  // #F2F3F5 — the question strip is gray in the reference, and only the main
  // exam header is white.
  expectFlushRail('question header', readings.questionHeader, 'rgb(242, 243, 245)');
});

test('wears the identical fixed-pixel barcode on both hosts', async ({ page }) => {
  const readings = await readRails(page);
  const { topbar, questionHeader } = readings;
  // ONE generated pattern, read through the same tokens by both hosts.
  expect(questionHeader.railBackgroundImage).toBe(topbar.railBackgroundImage);
  expect(questionHeader.railBackgroundSize).toBe(topbar.railBackgroundSize);
  expect(questionHeader.railBox.height).toBe(topbar.railBox.height);
  // Fixed pixels, never percentages: a percentage stop would stretch with each
  // host's width (1440px vs the strip's ~639px) and the two rails would differ.
  expect(topbar.railBackgroundImage, 'the rail must not be a stretched gradient').not.toContain('%');
  expect(topbar.railBackgroundImage).toMatch(/px/);
  expect(topbar.railBackgroundRepeat).toBe('repeat-x');
  // The pattern is longer than the strip and tiles: the tile length is a pixel
  // length, so the barcode never rescales with the container.
  expect(topbar.railBackgroundSize).toMatch(/^\d+(\.\d+)?px 100%$/);
});

test('degrades to one system separator in forced colors', async ({ page }) => {
  await page.emulateMedia({ forcedColors: 'active' });
  const readings = await readRails(page);
  for (const [name, rail] of [
    ['top bar', readings.topbar],
    ['question header', readings.questionHeader],
  ] as const) {
    // Decorative segments are dropped, never repainted into system colours: the
    // rail is the browser's own separator ink now (Chrome resolves the system
    // keyword to a concrete value, so the check is that no rail colour survived).
    expect(rail.railBackgroundImage, `${name} rail keeps no decorative layers`).toBe('none');
    expect([rail.light, rail.blue, rail.yellow], `${name} rail wears no rail colour`).not.toContain(
      rail.railBackgroundColor,
    );
    // The header still has a visible bottom edge, still flush with its host.
    expect(rail.railBox.height).toBeGreaterThan(0);
    expect(Math.abs(rail.railBox.bottom - rail.hostBox.bottom), `${name} separator still closes the host`).toBeLessThanOrEqual(0.5);
  }
});

test('locks the chrome pixels against the supplied reference crops', async ({ page }) => {
  const supplied = REFERENCE_REGIONS.filter((region) => existsSync(join(REFERENCE_DIR, region.file)));
  test.skip(
    supplied.length === 0,
    `No reference crops supplied. Put the Bluebook crops in e2e/fixtures/sat-rail-reference/ ` +
      `(${REFERENCE_REGIONS.map((region) => region.file).join(', ')}) — this comparison is the acceptance gate, ` +
      `and it compares against the reference, never against a snapshot of our own output.`,
  );

  const applied = new Set<string>();
  const applyStates = async (states: string[]) => {
    for (const state of states) {
      if (applied.has(state)) continue;
      applied.add(state);
      if (state === 'marked') {
        await page.getByRole('button', { name: 'Mark for Review' }).click();
        await expect(page.getByRole('button', { name: 'Marked for Review' })).toBeVisible();
      } else if (state === 'eliminator') {
        await page.getByRole('button', { name: 'Turn on cross-out mode' }).click();
        await expect(page.getByRole('button', { name: 'Turn off cross-out mode' })).toHaveAttribute(
          'aria-pressed',
          'true',
        );
      }
    }
  };

  for (const region of supplied) {
    await applyStates(region.states);
    const anchor =
      region.anchor === 'question-header'
        ? page.locator(RAIL).nth(1).locator('..')
        : page.locator(region.anchor);
    const box = await anchor.boundingBox();
    if (!box) throw new Error(`${region.file}: the live region is not rendered.`);
    const reference = readPngSize(join(REFERENCE_DIR, region.file));
    // The crop is anchored to the host's bottom edge (where the rail lives), so
    // a 3px rail-only crop and a full-strip crop both align without a re-cut.
    if (reference.width > box.width + 0.5) {
      throw new Error(
        `${region.file} is ${reference.width}px wide but the live region is ${box.width}px: ` +
          `re-cut the crop at the ${VIEWPORT.width}x${VIEWPORT.height} reference viewport.`,
      );
    }
    await expect(page).toHaveScreenshot(region.file, {
      clip: {
        x: box.x,
        y: box.y + box.height - reference.height,
        width: reference.width,
        height: reference.height,
      },
      animations: 'disabled',
    });
  }
});
