package authoringcoedit

import (
	"encoding/hex"
	"strconv"
	"strings"
)

// DecimalString is the JSON representation of a BIGINT counter. It is kept as
// a string at protocol boundaries so JavaScript cannot round an epoch or
// acknowledgement sequence before comparing it.
type DecimalString string

const maxDecimalStringDigits = 20

// IsDecimalString accepts the canonical, non-negative uint64 spelling used on
// co-edit JSON boundaries. Leading zeroes are rejected so the same counter has
// one wire representation everywhere.
func IsDecimalString(value string) bool {
	if len(value) == 0 || len(value) > maxDecimalStringDigits {
		return false
	}
	if len(value) > 1 && value[0] == '0' {
		return false
	}
	for index := 0; index < len(value); index++ {
		if value[index] < '0' || value[index] > '9' {
			return false
		}
	}
	_, err := strconv.ParseUint(value, 10, 64)
	return err == nil
}

// ParseDecimalString converts a validated wire counter for database or state
// machine work. Callers that only relay the value should keep it as text.
func ParseDecimalString(value string) (uint64, bool) {
	if !IsDecimalString(value) {
		return 0, false
	}
	parsed, err := strconv.ParseUint(value, 10, 64)
	return parsed, err == nil
}

// CoeditLifecycleOperation identifies the freeze owner and its expiry. The
// expiry uses Unix seconds because it is a timestamp, not an unbounded counter.
type CoeditLifecycleOperation struct {
	FreezeOperationID string `json:"freezeOperationId"`
	FreezeExpiresAt   int64  `json:"freezeExpiresAt"`
}

// Valid reports whether an operation can safely own a lifecycle fence.
func (o CoeditLifecycleOperation) Valid() bool {
	return IsLifecycleOperationID(o.FreezeOperationID) && o.FreezeExpiresAt > 0
}

// IsLifecycleOperationID accepts the opaque identifier shape generated by the
// service. The database migration stores it in CHAR(36), so the protocol keeps
// the same maximum while remaining independent of UUID parsing.
func IsLifecycleOperationID(value string) bool {
	if len(value) == 0 || len(value) > 36 {
		return false
	}
	for index, char := range []byte(value) {
		if (char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z') ||
			(char >= '0' && char <= '9') || (index > 0 && (char == '-' || char == '_')) {
			continue
		}
		return false
	}
	first := value[0]
	return (first >= 'a' && first <= 'z') || (first >= 'A' && first <= 'Z') ||
		(first >= '0' && first <= '9')
}

// CoeditDurabilityMetadata is shared by rebase responses and cache recovery.
// StateHash is the lowercase SHA-256 provenance hash of the durable binary.
type CoeditDurabilityMetadata struct {
	Room               string        `json:"room"`
	StateEpoch         DecimalString `json:"stateEpoch"`
	StateHash          string        `json:"stateHash"`
	CommitSequence     DecimalString `json:"commitSequence"`
	SafeToDiscardCache bool          `json:"safeToDiscardCache"`
}

// Valid checks metadata before it is used to decide whether local cache data
// may be discarded or a room may be rebased.
func (m CoeditDurabilityMetadata) Valid() bool {
	if m.Room != strings.TrimSpace(m.Room) {
		return false
	}
	if _, _, _, err := ParseAnyDocumentName(m.Room); err != nil {
		return false
	}
	if !IsDecimalString(string(m.StateEpoch)) || !IsDecimalString(string(m.CommitSequence)) {
		return false
	}
	if len(m.StateHash) != sha256HexBytes*2 {
		return false
	}
	_, err := hex.DecodeString(m.StateHash)
	return err == nil
}

const sha256HexBytes = 32
