import {act,fireEvent,render,screen} from '@testing-library/react';
import {Editor} from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import {TableKit} from '@tiptap/extension-table';
import {afterEach,describe,it,expect,vi} from 'vitest';
import {EditableBlockMath,EditableInlineMath} from '../EditableMathExtension';
import {SatImage} from '../SatImageExtension';
import {ComposerToolbar} from '../ComposerToolbar';
import {SAT_RICH_COMPOSER_CAPABILITIES as capabilities} from '../RichQuestionComposer';
const editors:Editor[]=[];afterEach(()=>editors.splice(0).forEach(e=>e.destroy()));
function make(content:object){const e=new Editor({extensions:[StarterKit,TableKit,EditableInlineMath,EditableBlockMath,SatImage],content});editors.push(e);return e;}
describe('contextual toolbar',()=>{
 it('edits and converts the selected equation without losing its expression',()=>{const e=make({type:'doc',content:[{type:'blockMath',attrs:{latex:'x^2'}}]});e.commands.setNodeSelection(0);const open=vi.fn();render(<ComposerToolbar editor={e} capabilities={capabilities} onOpenDialog={open} onTableMutation={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Edit equation'}));expect(open).toHaveBeenCalledWith('math',expect.objectContaining({pos:0,latex:'x^2',display:true}));fireEvent.click(screen.getByRole('button',{name:'Inline equation'}));expect(JSON.stringify(e.getJSON())).toContain('inlineMath');expect(JSON.stringify(e.getJSON())).toContain('x^2');});
 it('targets the selected image for metadata editing rather than inserting another',()=>{const e=make({type:'doc',content:[{type:'image',attrs:{src:'https://example.test/image.png',alt:'Graph',assetId:'asset-1'}}]});e.commands.setNodeSelection(0);const open=vi.fn();render(<ComposerToolbar editor={e} capabilities={capabilities} onOpenDialog={open} onTableMutation={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Edit alternative text'}));expect(open).toHaveBeenCalledWith('image',expect.objectContaining({pos:0,attrs:expect.objectContaining({assetId:'asset-1'})}));fireEvent.click(screen.getByRole('button',{name:'Delete image'}));expect(JSON.stringify(e.getJSON())).not.toContain('asset-1');});
 it('switches to table actions without mounting another toolbar',()=>{const e=make({type:'doc',content:[{type:'paragraph'}]});render(<ComposerToolbar editor={e} capabilities={capabilities} onOpenDialog={vi.fn()} onTableMutation={vi.fn()}/>);act(()=>{e.commands.insertTable({rows:2,cols:2});});expect(screen.getByRole('button',{name:'Add row'})).toBeInTheDocument();expect(screen.getAllByRole('toolbar')).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Table actions'}));fireEvent.click(screen.getByRole('menuitem',{name:'Delete table'}));expect(screen.getByRole('button',{name:'Insert content'})).toBeInTheDocument();});
 it('keeps undo and redo visible and functional in the text context',()=>{const e=make({type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Stem'}]}]});render(<ComposerToolbar editor={e} capabilities={capabilities} onOpenDialog={vi.fn()} onTableMutation={vi.fn()}/>);expect(screen.getByRole('button',{name:'Undo (⌘Z)'})).toBeDisabled();act(()=>{e.commands.insertContentAt(5,' more');});const undo=screen.getByRole('button',{name:'Undo (⌘Z)'});expect(undo).toBeEnabled();fireEvent.click(undo);expect(e.state.doc.textContent).toBe('Stem');const redo=screen.getByRole('button',{name:'Redo (⇧⌘Z)'});expect(redo).toBeEnabled();fireEvent.click(redo);expect(e.state.doc.textContent).toBe('Stem more');});
 it('shows contextual actions alongside the standard controls in every node context',()=>{const renderToolbar=(editor:Editor)=>render(<ComposerToolbar editor={editor} capabilities={capabilities} onOpenDialog={vi.fn()} onTableMutation={vi.fn()}/>);const table=make({type:'doc',content:[{type:'paragraph'}]});const a=renderToolbar(table);act(()=>{table.commands.insertTable({rows:2,cols:2,withHeaderRow:true});});expect(a.getByRole('button',{name:'Add row'})).toBeInTheDocument();expect(a.getByRole('combobox',{name:'Text style'})).toBeInTheDocument();expect(a.getByRole('button',{name:'Bold (⌘B)'})).toBeInTheDocument();expect(a.getByRole('button',{name:'Undo (⌘Z)'})).toBeEnabled();a.unmount();const equation=make({type:'doc',content:[{type:'blockMath',attrs:{latex:'x^2'}}]});equation.commands.setNodeSelection(0);const b=renderToolbar(equation);expect(b.getByRole('button',{name:'Edit equation'})).toBeInTheDocument();expect(b.getByRole('button',{name:'Italic (⌘I)'})).toBeInTheDocument();expect(b.getByRole('button',{name:'Undo (⌘Z)'})).toBeInTheDocument();b.unmount();const image=make({type:'doc',content:[{type:'image',attrs:{src:'https://example.test/i.png',alt:'Graph',assetId:'a1'}}]});image.commands.setNodeSelection(0);const c=renderToolbar(image);expect(c.getByRole('button',{name:'Edit alternative text'})).toBeInTheDocument();expect(c.getByRole('button',{name:'More formatting'})).toBeInTheDocument();expect(c.getByRole('button',{name:'Redo (⇧⌘Z)'})).toBeInTheDocument();});
 it('keeps undo and redo out of the overflow menu once they are visible buttons',()=>{const e=make({type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Stem'}]}]});render(<ComposerToolbar editor={e} capabilities={capabilities} onOpenDialog={vi.fn()} onTableMutation={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'More formatting'}));expect(screen.queryByRole('menuitem',{name:'Undo'})).toBeNull();expect(screen.queryByRole('menuitem',{name:'Redo'})).toBeNull();});
});
