-- PostgreSQL NOTIFY trigger removed
-- pg_notify is PostgreSQL-specific and not available in MySQL/TiDB
-- Real-time outbox wakeups will be handled by:
-- 1. Application-level polling (existing fallback mechanism)
-- 2. Redis pub/sub (if implemented)
-- 3. Or other message queue system
